### ISSUE TITLE
Video not showing

### ISSUE THREAD

**Issue by LDanchenko** [jitsi/jitsi-meet-torture#418]
Hello!

We started to use malleus.sh script with selenium grid:

./scripts/malleus.sh --conferences=1 --participants=20  --senders=10  --audio-senders=10  --duration=210 --room-name-prefix=Brawnewtest --hub-url=http://ip:4444/wd/hub --instance-url=https://jitsiturl.com --debug

But we see less video senders in conference, we run scripts with debug options, but script did not notify any errors:

[WARNING] Tests run: 406, Failures: 0, Errors: 0, Skipped: 405, Time elapsed: 303.027 s - in TestSuite
[INFO]
[INFO] Results:
[INFO]
[WARNING] Tests run: 400, Failures: 0, Errors: 0, Skipped: 399
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  05:05 min
[INFO] Finished at: 2021-09-14T14:40:42-04:00
[INFO] ------------------------------------------------------------------------

https://prnt.sc/1saqdz2

**Comment by saghul** [comment]
Do you have `startAudioMuted` and `startVideoMuted` configured in your deployment?

**Comment by damencho** [comment]
Also, make sure your selenium nodes are not overloaded.

**Comment by LDanchenko** [comment]
I did not set startAudioMuted and startVideoMuted, where I should set it?

**Comment by damencho** [comment]
> I did not set startAudioMuted and startVideoMuted, where I should set it?

On the deployment you test.

**Comment by damencho** [comment]
> I am running selenium nodes:
> java -Dwebdriver.chrome.driver=chromedriver -jar selenium-server-standalone-3.141.59.jar -role node -nodeConfig node.json -debug
> with json configuration "maxInstances": 100,
> because we need to run test with at least 100 users on server with 40 cores.

Check the CPU and RAM usage on the machine ... we had always tested this with many nodes, not with a single powerful node ...

**Comment by LDanchenko** [comment]
Thank you, we started running test with 100 senders, but all videos are blinking. Also I can see that there is no load on the jitsi server. I ran selenium chrome on different nodes, 10 chrome on node. Could you tell me please, what the problem is? We used video in .y4m format.

**Comment by LDanchenko** [comment]
Also we set startAudioMuted and startVideoMuted in jitsi, all videos are displayed, but blink - disappear and appear.

**Comment by saghul** [comment]
That might be a bug in the JVB and not in your setup 😨

**Comment by LDanchenko** [comment]
@damencho please tell me what you think about this issue?

**Comment by damencho** [comment]
Where do you put the video file?

**Comment by LDanchenko** [comment]
Video in resources directory, on node with Selenium hub.

**Comment by damencho** [comment]
You mean the file FourPeople_1280x720_30.y4m is in /usr/share/jitsi-meet-torture/resources/?

Wait you say videos are blinking? You mean, there is video you just see it blinking when you join the load test room and your 100 senders are in?

**Comment by damencho** [comment]
Try being 3 participants in the room (so no p2p) ... wait for at least 30 seconds so your bandwidth estimation can ramp up on the bridge and then start the test with 100 senders, does that change anything?

**Comment by Omaca** [comment]
Hi
I also have the same problem, can't see the video. Below is the summay of my environment status:

1. run with command ./scripts/malleus.sh --conferences=1 --participants=3 --senders=1 --duration=300 --room-name-prefix=omatest --hub-url=http://localhost:4444/wd/hub --instance-url=https://{self-host-domain}
2. run with Selenium Grid installed on same desktop, and copy the resources to the docker (the docker image was built from selenium/node-chrome:beta)
<img width="466" alt="image" src="https://github.com/jitsi/jitsi-meet-torture/assets/5716890/1a65edc6-9809-478f-8deb-58794455db6f">  

3.  Jitsi server keep startAudioMuted and startVideoMuted as masked, without modified
4. Test desktop loading: cpu ~25% and memory ~65%
5. The Selenium node screen as below(no video show)
<img width="756" alt="image" src="https://github.com/jitsi/jitsi-meet-torture/assets/5716890/b85db2a3-b841-4134-b65a-57128aaa98f0">

Any suggestion about this?

BR.
Omaca

**Comment by damencho** [comment]
Are you using this docker file to build the images?
https://github.com/jitsi/jitsi-meet-torture/blob/master/doc/grid/Dockerfile

Like this
https://github.com/jitsi/jitsi-meet-torture/tree/master/doc/grid#images

**Comment by damencho** [comment]
The guide there should be working, follow that to create the grid and use it.

**Comment by Omaca** [comment]
@damencho 


I try, but still can't get the video show.
<img width="556" alt="image" src="https://github.com/jitsi/jitsi-meet-torture/assets/5716890/2939a8f4-60f4-4ab5-b0c9-67ceff3cc305">

I run on GCP VM with 6vcpu/24G, the loading 40% cpu usage, and 15% memory usage.

**Comment by srdjan-job-com** [comment]
I can confirm that i am also not seeing any video.
When i check from docker container 
`sudo docker run jitsi/standalone-chrome ls /usr/share/jitsi-meet-torture/resources
fakeAudioStream_license.txt
fakeAudioStream-lipsync.wav
fakeAudioStream.wav
fakeVideoStream.y4m
FourPeople_1280x720_30.y4m
PSNRVideoOperator.js
`
I can see that video is in proper location, but when i join the test conference neither of participants have video.
Do we need to set any specific variable or something else to point to this video prior to starting test ? @damencho

**Comment by srdjan-job-com** [comment]
Ou i figured out that it have something to do with senders_per_node and senders_per_tab.
When i deleted those arguments i can now see the video.
Maybe because use-load-test was not set ? 
Do we need any specific config on jitsi-meet to be enable in order for this to work properly
